const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{Sólido: 0},
	{Fisico: 0},
	{nFisico: 0},
	{fisico2: 0},
	{fisico3: 0},
	{barreira: 0},
	{circo: 0},
	{Sprite2: 0},
	{paredes: 0},
	{chão: 0},
	{ScrollTo: 0},
	{camera: 0},
	{hp: 0},
	{"8Direction": 0},
	{Solid: 0},
	{ghost: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{hitbox: 0},
	{tomandodano: 0},
	{Flash: 0},
	{Timer: 0},
	{jogador: 0},
	{Variable1: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{boss: 0},
	{batman: 0},
	{Audio: 0},
	{Sprite5: 0},
	{Text: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Text2: 0},
	{Button: 0},
	{Sprite4: 0},
	{start: 0},
	{reiniciar: 0},
	{exit: 0},
	{vidas: 0},
	{dinherostotais: 0},
	{dinheiroscoletados: 0}
];

self.InstanceType = {
	vida: class extends self.ISpriteInstance {},
	Fisico: class extends self.ITilemapInstance {},
	nFisico: class extends self.ITilemapInstance {},
	fisico2: class extends self.ITilemapInstance {},
	fisico3: class extends self.ITilemapInstance {},
	barreira: class extends self.ISpriteInstance {},
	circo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	paredes: class extends self.ITilemapInstance {},
	chão: class extends self.ITilemapInstance {},
	camera: class extends self.ISpriteInstance {},
	ghost: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	hitbox: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	batman: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {}
}